### ISSUE TITLE
NameError: global name 'ncorr' is not defined

### ISSUE THREAD

**Issue by andrewfowlie** [yabebalFantaye/MCEvidence#5]
Running 

`python examples.py`

I find

```
Using example:  gaussian_eg
Calling sampler to get MCMC chain: nsamples= 10000


mean_sample= [ 1.01633322  2.01635676  3.00255462  4.0087787   5.01464661  5.99930579
  6.99864216  7.98727022  9.01328165  9.99536056]
std_sample= [ 1.00429329  0.99534895  1.00201124  0.99014497  1.00622132  0.99728491
  1.00370805  0.99203203  0.9886086   1.0029923 ]

samples and loglikes shape:  (10000, 10) (10000,)
INFO:MCEvidence:Removed 0.1 as burn in
INFO:MCEvidence:applying weighted thinning with thin length=2
INFO:MCEvidence:Thinning not possible.
Traceback (most recent call last):
  File "examples.py", line 559, in <module>
    mce=MCEvidence(chain,thinlen=2,burnlen=0.1,verbose=2,ischain=True).evidence()
  File "/home/andrew/evidence/MCEvidence/MCEvidence.py", line 627, in __init__
    _=self.gd.thin(nthin=thinlen)        
  File "/home/andrew/evidence/MCEvidence/MCEvidence.py", line 470, in thin
    ixw_dict = weighted_thin(self.weights,ncorr)
NameError: global name 'ncorr' is not defined
```

**Comment by yabebalFantaye** [comment]
Fixed in the latest version.
