### ISSUE TITLE
Bug in version 2?

### ISSUE THREAD

**Issue by ivandebono** [yabebalFantaye/MCEvidence#8]
There seems to be a bug in the latest version of MCEvidence. It occurs at the point where the chains are read and the dimension is determined. Here is the error message I get when I try to run planck_mcevidence:
chains2samples kwargs;  dict_keys(['thinlen', 'burnlen'])
Traceback (most recent call last):
  File "planck_mcevidence.py", line 347, in <module>
    thinlen=thinfrac).evidence(info=True,pos_lnp=False)
  File "/mcevidence/MCEvidence.py", line 754, in __init__
    self.gd = MCSamples(method,csplit=csplit,debug=self.debug,**gdkwargs)
  File "/mcevidence/MCEvidence.py", line 558, in __init__
    self.setup(str_or_dict,**kwargs)
  File "/mcevidence/MCEvidence.py", line 143, in setup
    self.data = self.load_from_file(fileroot,**kwargs)
  File "/mcevidence/MCEvidence.py", line 607, in load_from_file
    return self.chains2samples(**kwargs)
  File "/mcevidence/MCEvidence.py", line 209, in chains2samples
    self.samples=np.concatenate(self.chains)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by ivandebono** [comment]
UPDATE:
I think I spotted the problem. The function np.concatenate cannot be used as given. The code uses the default axis=0. If you use axis=None to resolve the above error, you end up with a 1-dimensional array instead of a 2-dimensional array. You need to use vstack. 

The line should be changed to self.samples=np.vstack(self.chains)

**Comment by yabebalFantaye** [comment]
[np.concatenate](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.vstack.html#numpy.vstack)(*, axis=0) is equivalent to np.vstack, so I am not sure why you got the error. I am not experiencing any issue. Do you have the same issue with planck chains?

**Comment by ivandebono** [comment]
First of all, a correction: the problem is not np.concatenate. I'll explain below.

I get the error with the Planck chains. I should point out I'm using Python 3.6.6 and GetDist 0.3.0.

I think it might be the way the root names are read and passed on to MCEvidence. 

The Planck folders for the data sets for each model contain different chains computed with different parameters, e.g.: If you have the folder 'base' with subfolder 'PlikEtcEtc', you may have roots called '.../base_PlikEtcEtc_JLA' (where the chains have, m columns) and '.../base_PlikEtcEtc_JLA_postBAOEtcEtc' (where the chains have n columns). And n is not equal to m.

The code reads in all the different roots, but when you pass method='base_PlikEtcEtc_JLA_' to MCEvidence, it searches for all the text files starting with that root. So it will include the '_postBAOEtcEtc' files. Then it tries to concatenate the chain arrays for both roots, which have different column sizes.

In the end, I solved the problem by writing my own module to collect all the model and dataset names, and all the roots, and to pass on the different roots separately in the parameter 'method'. I then used MCEvidence as usual, and it worked just fine. 

I'll upload the code on my Github repository later.

**Comment by ivandebono** [comment]
Update: I tweaked your code, and it's now reading the chain files correctly. 

However, it gives an error when the importance sampling function h0_gauss_lnp is called:

  File "planck_mcevidence.py", line 57, in h0_gauss_lnp
    frac=(ParSamples.H0 - H0)/H0_Err
AttributeError: 'numpy.ndarray' object has no attribute 'H0'

ParSamples is a Numpy array, not a GetDist object. I think what you need here is either to call
H0=getdist.loadMCSamples(root).getParams().H0 or to define a method to output the 'H0' column in the array.

**Comment by ivandebono** [comment]
Update: I modified the code to allow the extractio of the H0 column in ParSamples. I uploaded the modified files to my MCEvidence fork.
